"""populate

Revision ID: 37f40bca79eb
Revises: 08394269f4ab
Create Date: 2023-03-21 17:45:17.432349

"""
from alembic import op
import sqlalchemy as sa

import pandas as pd
from nba_backend.database import engine
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '37f40bca79eb'
down_revision = '08394269f4ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    teamstat_df = pd.read_csv("../backend/db-files/teamstat/teamstat_2016_regular_filled.csv", index_col=False)

    teamstat_df['GAME_DATE'] = teamstat_df['GAME_DATE'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d').date())
    teamstat_df.to_sql('teamstat', engine, if_exists='append', index=False)

    gamelog_df = pd.read_csv("../backend/db-files/gamelog/gamelog_2016_regular.csv", index_col=False)

    gamelog_df['GAME_DATE'] = gamelog_df['GAME_DATE'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d').date())
    gamelog_df.drop(columns=["T1_L", "T2_L", "T1_L_cum", "T2_L_cum"], inplace=True)
    gamelog_df.to_sql('gamelog', engine, if_exists='append', index=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    con = engine.connect()
    con.execute(sa.text("TRUNCATE TABLE teamstat;"))
    con.execute(sa.text("TRUNCATE TABLE gamelog;"))
    con.commit()
    con.close()
    # ### end Alembic commands ###
